version: "2"
services:
  dev:
    build:
      context: .
      args:
        builder: 'false'
    command: go run main.go
    volumes:
      - ./:/go
    ports:
      - 8080:80
    environment:
      MULTICAST_HTTP_HEADER: My-Custom_header
      MULTICAST_HTTP_HEADER_VALUE: any_header
      MULTICAST_HTTP_HOSTS: yandex.ru,https://google.ru
      MULTICAST_HTTP_DEBUG: 1
      # MULTICAST_HTTP_K8S_POD_LABEL: 'app: test'
      # MULTICAST_HTTP_K8S_POD_PORT: 8080
  prod:
    build:
      context: .
    ports:
      - 8080:80
    environment:
      MULTICAST_HTTP_HEADER: My-Custom_header
      MULTICAST_HTTP_HEADER_VALUE: any_header
      MULTICAST_HTTP_HOSTS: yandex.ru,https://google.ru
      MULTICAST_HTTP_DEBUG: 1
      # MULTICAST_HTTP_K8S_POD_LABEL: 'app: test'
      # MULTICAST_HTTP_K8S_POD_PORT: 8080